<script src="/js/Chart.min.js"></script>
<#--    <#if adminmanager??>-->
<script src="/js/vacation-sse.js"></script>
<#--    </#if>-->
<!-- Page level custom scripts -->
<!-- <script src="js/demo/chart-area-demo.js"></script> -->
<script src="/js/demo/chart-bar-demo.js"></script>
<script src="/js/demo/chart-bar-team.js"></script>
<script src="/js/demo/chart-bar-employee.js"></script>
<script src="/js/demo/chart-pie-demo.js"></script>
